### ISSUE TITLE
External mode not functioning with Plover

### ISSUE THREAD

**Issue by garinl** [ezyang/stenomatic#2]
When I select 'Type as shown', I cannot input text via Plover.

**Comment by ezyang** [comment]
Oof, you're right, it looks broken.

**Comment by garinl** [comment]
Besides that, I really like your program and I appreciate all the effort
you've put in to help others learn on Plover.  Thanks!  Looking forward to
seeing the bug fixed!

**Comment by ezyang** [comment]
Should be fixed, I think!
